[[permission]]
identifier = "allow-sync"
description = "Enables git sync commands."
commands.allow = [
  "get_git_status",
  "git_init",
  "git_list_remotes",
  "git_add_remote",
  "git_remove_remote",
  "git_pull",
  "git_sync_push",
  "git_http_request",
  "get_file_diff",
  "revert_file_change"
]
